#!/usr/bin/with-contenv bash


PUID=${PUID:-911}
PGID=${PGID:-911}

if [ ! "$(id -u abc)" -eq "$PUID" ]
then 
    usermod -o -u "$PUID" abc
fi

if [ ! "$(id -g abc)" -eq "$PGID" ]
then 
    groupmod -o -g "$PGID" abc
fi

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
